shop/products/urls.py
from django.conf.urls import url, include
from products.views import ProductList, ProductDetail, CategoryProductList, SubcategoryProductList, ProductCommentCreate, TagIndexView, SearchListView, SearchAutocompleteView, ProductCommentList

urlpatterns = [
    url(r'^products/$', ProductList.as_view(), name='products'),
    url(r'^products/(?P<product_category>\w+)/$', CategoryProductList.as_view(), name='products_category'),
    url(r'^products/(?P<product_category>\w+)/(?P<product_subcategory>\w+)/$', SubcategoryProductList.as_view(), name='products_subcategory'),
    url(r'^products/(?P<product_category>\w+)/(?P<product_subcategory>\w+)/(?P<pk>\w+)/', include([
            url( r'^$', ProductDetail.as_view(), name = 'product'),
            url(r'^comment/$', ProductCommentCreate.as_view(), name='product_comment'),
            url(r'^comments/$', ProductCommentList.as_view(), name='product_comments'),

        ])),
    url(r'^tag/(?P<slug>[-\w]+)/$', TagIndexView.as_view(), name='tagged'),
    url(r'^search/$', SearchListView.as_view(), name='search'),
    url(r'^autocomplete/$', SearchAutocompleteView.as_view(), name='autocomplete'),
]

shop/shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import SignUpView, SignInView, SignOutView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signin/$', SignInView.as_view(), name='signin'),
    url(r'^signout/$', SignOutView.as_view(), name='signout'),
    url(r'^', include('landing.urls')),
    url(r'^', include('products.urls')),
    url(r'^', include('orders.urls')),
    url(r'^', include('contact.urls')),
] \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/products/models.py
from django.db import models

import os.path
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile
from taggit.managers import TaggableManager


class Category(models.Model):
    category_name = models.SlugField(max_length=128, blank=True, null=True, default=None, unique=True)

    def __str__(self):
        return "%s" % self.category_name


class Subcategory(models.Model):
    category = models.ForeignKey(Category, blank=True, null=True, default=None)
    subcategory_name = models.SlugField(max_length=128, blank=True, null=True, default=None)
    subcategory_image = models.ImageField(upload_to='products_images/',default=None)

    def __str__(self):
        return "%s" % self.subcategory_name

    def image_tag(self):
        return u'<img src="%s" />' % self.subcategory_image.url
    image_tag.short_description = 'Image'
    image_tag.allow_tags = True

class Product(models.Model):

    SIZES = (
        ('XS','XS'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
    )
    category = models.ForeignKey(Category, blank=True, null=True, default=None)
    subcategory = models.ForeignKey(Subcategory, blank=True, null=True, default=None)
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    description = models.TextField(blank=True, null=True, default=None)
    sizes = models.CharField(max_length=2, choices=SIZES, default='XS')

    tags = TaggableManager()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s/%s - %s: %s $" % (self.category, self.subcategory, self.name, self.price)

class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='products_images/')
    thumbnail = models.ImageField(upload_to='thumbnails/', max_length=500, null=True, blank=True, editable=False)
    is_main = models.BooleanField(default=False)

    def save(self, *args, **kwargs):

        if not self.make_thumbnail():
            # set to a default thumbnail
            raise Exception('Could not create thumbnail - is the file type valid?')

        super(ProductImage, self).save(*args, **kwargs)

    def make_thumbnail(self):

        THUMBNAIL_SIZE = (200, 200)
        image = Image.open(self.image)
        image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)

        thumb_name, thumb_extension = os.path.splitext(self.image.name)
        thumb_extension = thumb_extension.lower()

        thumb_filename = thumb_name + '_thumb' + thumb_extension

        if thumb_extension in ['.jpg', '.jpeg']:
            FTYPE = 'JPEG'
        elif thumb_extension == '.gif':
            FTYPE = 'GIF'
        elif thumb_extension == '.png':
            FTYPE = 'PNG'
        else:
            return False  # Unrecognized file type

        # Save thumbnail to in-memory file as StringIO
        temp_thumb = BytesIO()
        image.save(temp_thumb, FTYPE)
        temp_thumb.seek(0)

        # set save=False, otherwise it will run in an infinite loop
        self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()

        return True

    def __str__(self):
        return "%s" % self.id

class ProductComment(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None)
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    comment = models.TextField(blank=True, null=True, default=None)

    def __str__(self):
        return "%s" % self.name

shop/products/forms.py
from django.forms import ModelForm
from .models import ProductComment

class ProductCommentForm(ModelForm):
    class Meta:
        model = ProductComment
        fields = ['name', 'comment']

shop/products/views.py
from django.http import JsonResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from django.views import View
from django.urls import reverse
from .forms import ProductCommentForm
from .models import Product, ProductImage, ProductComment
from taggit.models import Tag
from django.db.models import Q


class TagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TagMixin, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

class ProductDetail(TagMixin, DetailView):
    model = Product
    template_name = 'products/product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data(**kwargs)
        context['category'] = self.kwargs['product_category']
        context['title'] = self.kwargs['product_subcategory']
        context['tags'] = Tag.objects.filter(product__id=self.kwargs['pk'])
        return context

class ProductCommentCreate(FormView):
    template_name = 'products/product-comment.html'
    form_class = ProductCommentForm

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.product_id = self.kwargs['pk']
        instance.save()
        return super(ProductCommentCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('product',
                       kwargs={
                           'product_category': self.kwargs['product_category'],
                           'product_subcategory': self.kwargs['product_subcategory'],
                           'pk': self.kwargs['pk'],
                       })

class ProductCommentList(TagMixin, ListView):
    model = ProductComment
    template_name = 'products/product-comments.html'
    context_object_name = 'comments'
    paginate_by = 6

    def get_queryset(self):
        comments = ProductComment.objects.filter(product__id = self.kwargs['pk'])
        return comments

    def get_context_data(self, **kwargs):
        context = super(ProductCommentList, self).get_context_data(**kwargs)
        context['category'] = self.kwargs['product_category']
        context['subcategory'] = self.kwargs['product_subcategory']
        context['product'] = self.kwargs['pk']
        return context

class ProductList(TagMixin, ListView):
    model = ProductImage
    template_name = 'products/products.html'
    context_object_name = 'products'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data(**kwargs)
        context['title'] = 'Products'
        return context

class CategoryProductList(ProductList):
    def get_queryset(self):
        products = ProductImage.objects.filter(product__category__category_name=self.kwargs['product_category'],
                                               is_main=True)
        return products

    def get_context_data(self, **kwargs):
        context = super(CategoryProductList, self).get_context_data(**kwargs)
        context['title'] = self.kwargs['product_category']
        return context

class SubcategoryProductList(ProductList):
    def get_queryset(self):
        products = ProductImage.objects.filter(product__category__category_name=self.kwargs['product_category'],
                                               is_main=True) \
                                        .filter(product__subcategory__subcategory_name=self.kwargs['product_subcategory'])
        return products

    def get_context_data(self, **kwargs):
        context = super(SubcategoryProductList, self).get_context_data(**kwargs)
        context['category'] = self.kwargs['product_category']
        context['title'] = self.kwargs['product_subcategory']
        return context

class TagIndexView(TagMixin, ListView):
    model = ProductImage
    template_name = 'products/products.html'
    context_object_name = 'products'
    paginate_by = 6

    def get_queryset(self):
        return ProductImage.objects.filter(product__tags__slug=self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super(TagIndexView, self).get_context_data(**kwargs)
        context['title'] = self.kwargs.get('slug')
        return context

class SearchListView(ProductList):
    def get_queryset(self):
        query = self.request.GET['search']
        products = ProductImage.objects.filter(
                                                Q(product__name__icontains=query) |
                                                Q(product__subcategory__subcategory_name__icontains=query) |
                                                Q(product__category__category_name__icontains=query)
                                              )
        return products
    def get_context_data(self, **kwargs):
        context = super(SearchListView, self).get_context_data(**kwargs)
        context['title'] = self.request.GET['search']
        return context

class SearchAutocompleteView(View):
    def get(self, request):
        query = request.GET['query']
        products = Product.objects.filter(
                                                Q(name__icontains=query) |
                                                Q(subcategory__subcategory_name__icontains=query) |
                                                Q(category__category_name__icontains=query)
                                              )
        data = [product.name for product in products]
        return JsonResponse({'query': data})

shop/templates/products/base_product.html
{% extends 'base.html' %}

{% block breadcrumbs %}

{% endblock %}

{% block content %}
    {% block right_sidebar %}
        <div class="col-md-3 product-bottom">
                    <!--categories-->
                        <div class=" rsidebar span_1_of_left">
                                <h3 class="cate">Categories</h3>
                                     <ul class="menu-drop">
                                         {% for category in categories %}
                                            <li class="item1">
                                                <a href="">{{category.category_name}} </a>
                                                    <ul class="cute">
                                                        {% for subcategory in category.subcategory_set.all %}
                                                        <li class="subitem{{forloop.counter}}"><a href="{% url 'products_subcategory' category.category_name subcategory.subcategory_name %}">{{subcategory.subcategory_name}} </a></li>
                                                        {% endfor %}
                                                    </ul>
                                            </li>
                                         {% endfor %}
                                    </ul>
                            </div>
                        <!--initiate accordion-->
                                <script type="text/javascript">
                                    $(function() {
                                        var menu_ul = $('.menu-drop > li > ul'),
                                               menu_a  = $('.menu-drop > li > a');
                                        menu_ul.hide();
                                        menu_a.click(function(e) {
                                            e.preventDefault();
                                            if(!$(this).hasClass('active')) {
                                                menu_a.removeClass('active');
                                                menu_ul.filter(':visible').slideUp('normal');
                                                $(this).addClass('active').next().stop(true,true).slideDown('normal');
                                            } else {
                                                $(this).removeClass('active');
                                                $(this).next().stop(true,true).slideUp('normal');
                                            }
                                        });

                                    });
                                </script>
        <!--//menu-->
        <!--tag-->
                        <div class="tag">
                                <h3 class="cate">Tags</h3>
                            <div class="tags">
                                <ul>
                                    {% for tag in tags %}
                                    <li><a href="{% url 'tagged' tag.slug %}">{{ tag.name }}</a></li>
                                    {% endfor %}
                                <div class="clearfix"> </div>
                                </ul>
                        </div>
                    </div>
                </div>
                <div class="clearfix"> </div>
        </div>
    {% endblock %}
{% endblock %}

shop/templates/products/product-comment.html
{% extends 'products/base_product.html' %}

{% block content %}
    <div class="container ">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="check-out">
                <h2>Please write your comment</h2>
                <form action="" method="post" class="form-checkout-order">
                    {% csrf_token %}
                    {{ form.as_p }}
                   <p><input type="submit" value="Submit" /></p>
                </form>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

shop/templates/products/product-comments.html
{% extends 'products/base_product.html' %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: slideInLeft;">
                <li>
                    <a href="{% url 'home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
                    </a>
                </li>

                {% if category %}
                     <li class="active">{{ category |title }}</li>
                {% endif %}

                {% if subcategory %}
                     <li class="active">{{ subcategory |title }}</li>
                {% endif %}

                <li class="active">{{ title |title }}</li>
			</ol>
		</div>
    </div>
{% endblock %}

{% block content %}
    <div class="single">
        <div class="container">
            <div class="col-md-12">
                <div class="comments">
                    <h2>Comments to product</h2>
                        {% for comment in comments %}
                            <div class="comment-item">
                                <h4>{{ comment.name }}</h4>
                                <p>{{ comment.comment }}</p>
                            </div>
                        {% endfor %}
                        <a class="comments__add" href="{% url 'product_comment' category subcategory product %}">Add comment</a>
                </div>
            </div>
        </div>
         <div class="container">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                    {% block pagination %}
                      {% if is_paginated %}
                          <div class="pagination">
                              <span class="page-links">
                                  {% if page_obj.has_previous %}
                                      <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                  {% endif %}
                                  <span class="page-current">
                                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                  </span>
                                  {% if page_obj.has_next %}
                                      <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                  {% endif %}
                              </span>
                          </div>
                      {% endif %}
                    {% endblock %}
                </div>
            <div class="col-md-4"></div>
        </div>
    </div>
{% endblock %}

shop/templates/products/product.html
{% extends 'products/base_product.html' %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: slideInLeft;">
                <li>
                    <a href="{% url 'home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
                    </a>
                </li>

                {% if category %}
                     <li class="active">{{ category |title }}</li>
                {% endif %}

                {% if subcategory %}
                     <li class="active">{{ subcategory |title }}</li>
                {% endif %}

                <li class="active">{{ title |title }}</li>
			</ol>
		</div>
    </div>
{% endblock %}

{% block content %}
    <div class="single">
        <div class="container">
            <div class="col-md-9">
                <div class="col-md-5 grid">
                <div class="flexslider">
                      <ul class="slides">
                          {% for image_item in product.productimage_set.all %}
                        <li data-thumb="{{ image_item.image.url }}">
                            <div class="thumb-image"> <img src="{{ image_item.image.url }}" data-imagezoom="true" class="img-responsive"> </div>
                        </li>
                          {% endfor %}
                      </ul>
                </div>
            </div>
                <div class="col-md-7 single-top-in">
                    <div class="single-para simpleCart_shelfItem">
                        <h2>{{product.name}}</h2>
                        <p>{{product.description}}</p>

                        <label  class="add-to item_price">${{product.price}}</label>
                        <div class="available">
                            <h6> Size - {{product.sizes}}</h6>
                        </div>
                        <a class="cart item_add" data-id="{{ product.id }}">Add to cart</a>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <div class="tag">
                        <h3 class="cate">Tags</h3>
                        <div class="tags">
                            <ul>
                                {% for tag in tags %}
                                    <li><a href="{% url 'tagged' tag.slug %}">{{ tag.name }}</a></li>
                                    {% endfor %}
                                <div class="clearfix"> </div>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="comments">
                        <h2>Comments to product</h2>
                            {% for comment in product.productcomment_set.all|slice:":3"%}
                                <div class="comment-item">
                                    <h4>{{ comment.name }}</h4>
                                    <p>{{ comment.comment }}</p>
                                </div>
                            {% endfor %}
                            {% if product.productcomment_set.count > 3 %}
                                 <a href="{% url 'product_comments' product.category.category_name product.subcategory.subcategory_name product.id%}" class="comments__all">Show all coomments ({{ product.productcomment_set.count }})</a>
                            {% endif %}
                            <a class="comments__add" href="{% url 'product_comment' product.category.category_name product.subcategory.subcategory_name product.id %}">Add comment</a>
                    </div>

                </div>
            </div>
             {{ block.super }}
        </div>
    </div>

{% endblock %}

shop/templates/products/products.html
{% extends 'products/base_product.html' %}


{% block breadcrumbs %}
    <div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: slideInLeft;">
                <li>
                    <a href="{% url 'home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
                    </a>
                </li>

                {% if category %}
                     <li class="active">{{ category |title }}</li>
                {% endif %}

                {% if subcategory %}
                     <li class="active">{{ subcategory |title }}</li>
                {% endif %}

                <li class="active">{{ title |title }}</li>
			</ol>
		</div>
    </div>
{% endblock %}

{% block content %}
    <div class="products">
        <div class="container">
            <h2>{{title |title}}</h2>
            <div class="col-md-9">
                <div class="content-top1">
                    {% for product_item in products %}
                        <div class="col-md-4 col-md4">
                            <div class="col-md1 simpleCart_shelfItem">
                                <a href="{% url 'product' product_item.product.category.category_name product_item.product.subcategory.subcategory_name product_item.product.id %}">
                                    <img class="img-responsive" src="{{product_item.thumbnail.url}}" alt="" />
                                </a>
                                <h3><a href="">{{product_item.product.name}}</a></h3>
                                <div class="price">
                                        <h5 class="item_price">${{product_item.product.price}}</h5>
                                        <button class="item_add" data-id="{{ product_item.product.id }}">Add To Cart</button>
                                        <div class="clearfix"> </div>
                                </div>
                            </div>
                        </div>
                    {% if forloop.counter|divisibleby:3 %}
                    <div class="clearfix"> </div>

                    </div>
                 <div class="content-top1">
                        {% endif %}
                    {% empty %}
                         <h2>Sorry, no products in this list.</h2>
                    {% endfor %}
                 </div>
            </div>
            {{ block.super }}
            <div class="clearfix"> </div>
        </div>
        <div class="container">
            <div class="col-md-4"></div>
                <div class="col-md-4">
                    {% block pagination %}
                      {% if is_paginated %}
                          <div class="pagination">
                              <span class="page-links">
                                  {% if page_obj.has_previous %}
                                      <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                  {% endif %}
                                  <span class="page-current">
                                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                  </span>
                                  {% if page_obj.has_next %}
                                      <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                  {% endif %}
                              </span>
                          </div>
                      {% endif %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
{% endblock %}